- hosts: servers
  tasks:
     - name: install yum
       yum: name=ntp state=latest
       become: true
     - name: copy ntp config file
       copy: src=~/ansible/ntp.conf dest=/etc/ntp.conf
       become: true
       notify:
         - check NTP config
     - name: check if NTP service is started
       service: name=ntpd state=started
       become: true
  handlers:
     - name: check NTP config
       service: name=ntpd state=restarted
       become: true
