- hosts: servers
  become: true
  tasks:
     - name: install mysql centos
       yum: name=mysql state=latest
       when: ansible_os_family == "RedHat"
     - name: install mysql ubuntu
       apt: name=mysql-server state=latest
       when: ansible_os_family == "Debian"
